options:
  formatter: stylish
  merge-default-rules: false
files:
  ignore:
    - 'assets/dist/**/*'
rules:
  attribute-quotes: 1
  brace-style: 1
  border-zero: 1
  empty-line-between-blocks: 1
  leading-zero:
    - 1
    - include: true
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 1
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-trailing-zero: 1
  no-vendor-prefixes: 2
  no-url-protocols: 2
  property-sort-order:
    - 1
    - order: smacss
  quotes:
    - 2
    - style: double
  one-declaration-per-line: 1
  single-line-per-selector: 1
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-brace: 2
  space-between-parens:
    - 1
    - include: true
  trailing-semicolon: 2

